# Generated by Django 2.1.3 on 2018-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_index_in_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owned',
            field=models.BooleanField(default=False, verbose_name='Owned'),
        ),
    ]
