# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahorro.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amount',
            name='when',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahorro.TimeInstant'),
            preserve_default=False,
        ),
    ]
