# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0002_auto_20170708_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Color'),
        ),
    ]
