# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0003_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(default='default.png', max_length=100, verbose_name='Icon'),
        ),
    ]
