# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlotState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('total_kms', models.IntegerField(default=0, verbose_name='Total kilometres')),
                ('partial_kms', models.FloatField(default=0, verbose_name='Partial kilometres')),
                ('litres', models.FloatField(default=0, verbose_name='Performance enhancer')),
                ('price', models.FloatField(default=0, verbose_name='Price (eur/L)')),
            ],
        ),
        migrations.CreateModel(
            name='VariableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Name')),
                ('long_name', models.CharField(default='long_name', max_length=100, verbose_name='Long name')),
                ('style', models.CharField(default='r', max_length=50, verbose_name='Plot style')),
                ('objective', models.IntegerField(default=1, verbose_name='Objective')),
            ],
        ),
    ]
